name: packer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with: 
          repository: freeze-dolphin/fragments-category
          ref: master
          token: ${{ secrets.CATEGORY_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: |
            fragments-category/songlist
            fragments-category/packlist
            fragments-category/unlocks
          overwrite: true